<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ck</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>ChucK</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return)\b</string>
			<key>name</key>
			<string>keyword.control.chuck</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.chuck</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escaped.chuck</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.chuck</string>
	<key>uuid</key>
	<string>15D5F74F-C569-4437-A935-036D85605FF8</string>
</dict>
</plist>
